### ISSUE TITLE
[Bug]: The simulation data task status is being executed and cannot be terminated (occasionally)

### ISSUE THREAD

**Issue by Huangxiao-mas** [oceanbase/odc#1650]
### ODC version

ODC424

### OB version

independent

### What happened?

The simulation data task status is being executed and cannot be terminated (occasionally)
![image](https://github.com/oceanbase/odc/assets/59468957/3408236e-e9c8-4b3c-ad8c-98688ef67054)
![image](https://github.com/oceanbase/odc/assets/59468957/b2e71e82-f652-4e97-8b27-7df27c2ac08a)
![image](https://github.com/oceanbase/odc/assets/59468957/4649cca5-fb5f-4c3a-bc37-3fc81b0e6c0e)

### What did you expect to happen?

Can be  terminated

### How can we reproduce it (as minimally and precisely as possible)?

chat priavtely

**Comment by yhilmare** [comment]
There is a difference of 0.1 seconds between the start of the task and the task inspection, which causes the inspection to start before the task actually starts. Then the inspection task throws a queue out-of-bounds exception. This problem is not expected to be thrown here, which leads to this unexpected circumstances
![lQLPKHMzfh1rAhvMws0KzLD_PbHq9SJukQXNE5Myv2kA_2764_194](https://github.com/oceanbase/odc/assets/22992296/521721fa-cbc6-497f-b143-b1ed8d1f9277)

**Comment by yhilmare** [comment]
```shell
[2024-02-28 11:07:52.905][Task-Periodically-Scheduled-0][2285f5de6cd34b08,fcff177e2efc,T4VTEA9CQPIWN10SCKBA7][WARN][com.oceanbase.odc.service.flow.task.BaseODCFlowTaskDelegate][112]: Task monitoring thread failed, taskId=37375
java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.LinkedList.checkElementIndex(LinkedList.java:559) ~[?:?]
	at java.util.LinkedList.get(LinkedList.java:480) ~[?:?]
	at com.oceanbase.odc.service.flow.task.MockDataRuntimeFlowableTask.isSuccessful(MockDataRuntimeFlowableTask.java:120) ~[odc-service-4.2.4-20240227.jar!/:?]
	at com.oceanbase.odc.service.flow.task.BaseODCFlowTaskDelegate.isCompleted(BaseODCFlowTaskDelegate.java:219) ~[odc-service-4.2.4-20240227.jar!/:?]
	at com.oceanbase.odc.service.flow.task.BaseODCFlowTaskDelegate.lambda$initMonitorExecutor$0(BaseODCFlowTaskDelegate.java:108) ~[odc-service-4.2.4-20240227.jar!/:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) [?:?]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305) [?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Thread.java:829) [?:?]
[2024-02-28 11:07:52.905][flowable-custom-async-job-executor-thread-26][,6b103474c85b,][WARN][com.oceanbase.odc.core.flow.BaseFlowableDelegate][53]: Service task execution failed
java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.LinkedList.checkElementIndex(LinkedList.java:559) ~[?:?]
	at java.util.LinkedList.get(LinkedList.java:480) ~[?:?]
	at com.oceanbase.odc.service.flow.task.MockDataRuntimeFlowableTask.isCancelled(MockDataRuntimeFlowableTask.java:82) ~[odc-service-4.2.4-20240227.jar!/:?]
	at com.oceanbase.odc.service.flow.task.BaseODCFlowTaskDelegate.run(BaseODCFlowTaskDelegate.java:156) ~[odc-service-4.2.4-20240227.jar!/:?]
	at com.oceanbase.odc.core.flow.BaseFlowableDelegate.execute(BaseFlowableDelegate.java:51) [odc-core-4.2.4-20240227.jar!/:?]
	at com.oceanbase.odc.service.flow.task.BaseRuntimeFlowableDelegate.execute(BaseRuntimeFlowableDelegate.java:135) [odc-service-4.2.4-20240227.jar!/:?]
	at org.flowable.engine.impl.delegate.invocation.JavaDelegateInvocation.invoke(JavaDelegateInvocation.java:35) [flowable-engine-6.3.1.jar!/:6.3.1]
	at org.flowable.engine.impl.delegate.invocation.DelegateInvocation.proceed(DelegateInvocation.java:35) [flowable-engine-6.3.1.jar!/:6.3.1]
	at org.flowable.engine.impl.delegate.invocation.DefaultDelegateInterceptor.handleInvocation(DefaultDelegateInterceptor.java:26) [flowable-engine-6.3.1.jar!/:6.3.1]
	at org.flowable.engine.impl.bpmn.behavior.ServiceTaskJavaDelegateActivityBehavior.execute(ServiceTaskJavaDelegateActivityBehavior.java:59) [flowable-engine-6.3.1.jar!/:6.3.1]
	at org.flowable.engine.impl.bpmn.helper.ClassDelegate.execute(ClassDelegate.java:203) [flowable-engine-6.3.1.jar!/:6.3.1]
	at org.flowable.engine.impl.agenda.ContinueProcessOperation.executeActivityBehavior(ContinueProcessOperation.java:258) [flowable-engine-6.3.1.jar!/:6.3.1]
	at org.flowable.engine.impl.agenda.ContinueProcessOperation.executeSynchronous(ContinueProcessOperation.java:155) [flowable-engine-6.3.1.jar!/:6.3.1]
	at org.flowable.engine.impl.agenda.ContinueProcessOperation.continueThroughFlowNode(ContinueProcessOperation.java:112) [flowable-engine-6.3.1.jar!/:6.3.1]
	at org.flowable.engine.impl.agenda.ContinueProcessOperation.run(ContinueProcessOperation.java:76) [flowable-engine-6.3.1.jar!/:6.3.1]
	at org.flowable.engine.impl.interceptor.CommandInvoker.executeOperation(CommandInvoker.java:88) [flowable-engine-6.3.1.jar!/:6.3.1]
	at org.flowable.engine.impl.interceptor.CommandInvoker.executeOperations(CommandInvoker.java:72) [flowable-engine-6.3.1.jar!/:6.3.1]
	at org.flowable.engine.impl.interceptor.CommandInvoker.execute(CommandInvoker.java:56) [flowable-engine-6.3.1.jar!/:6.3.1]
	at org.flowable.engine.impl.interceptor.BpmnOverrideContextInterceptor.execute(BpmnOverrideContextInterceptor.java:25) [flowable-engine-6.3.1.jar!/:6.3.1]
	at org.flowable.common.engine.impl.interceptor.TransactionContextInterceptor.execute(TransactionContextInterceptor.java:53) [flowable-engine-common-6.3.1.jar!/:6.3.1]
	at org.flowable.common.engine.impl.interceptor.CommandContextInterceptor.execute(CommandContextInterceptor.java:71) [flowable-engine-common-6.3.1.jar!/:6.3.1]
	at org.flowable.common.engine.impl.interceptor.LogInterceptor.execute(LogInterceptor.java:30) [flowable-engine-common-6.3.1.jar!/:6.3.1]
	at org.flowable.common.engine.impl.cfg.CommandExecutorImpl.execute(CommandExecutorImpl.java:56) [flowable-engine-common-6.3.1.jar!/:6.3.1]
	at org.flowable.common.engine.impl.cfg.CommandExecutorImpl.execute(CommandExecutorImpl.java:51) [flowable-engine-common-6.3.1.jar!/:6.3.1]
	at org.flowable.job.service.impl.asyncexecutor.ExecuteAsyncRunnable.executeJob(ExecuteAsyncRunnable.java:128) [flowable-job-service-6.3.1.jar!/:6.3.1]
	at org.flowable.job.service.impl.asyncexecutor.ExecuteAsyncRunnable.run(ExecuteAsyncRunnable.java:116) [flowable-job-service-6.3.1.jar!/:6.3.1]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) [?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Thread.java:829) [?:?]
[2024-02-28 11:07:52.906][ob-data-mocker-thread-2][,6b103474c85b,][INFO][com.oceanbase.tools.datamocker.core.task.MockDataBeforeTask][49]: Mock before task is running...
[2024-02-28 11:07:52.911][ob-data-mocker-thread-2][,6b103474c85b,][INFO][com.oceanbase.tools.datamocker.core.task.MockDataBeforeTask][51]: Mock before task is succeed
[2024-02-28 11:07:52.911][flowable-custom-async-job-executor-thread-26][,6b103474c85b,][WARN][com.oceanbase.odc.core.flow.BaseFlowableDelegate][73]: Exception has to be an instance of FlowException, pId=flow8551eee9b51a4b978435f7ec01530c67:1:1263435, activityId=flowc1d3547b2cba483197ea5b87a19c5e9f, acceptErrorCodes=[FlowTaskInstanceCancelled, FlowTaskInstanceFailed, FlowTaskInstanceExpired]

```
