### ISSUE TITLE
[Bug]: failed to mock data for a table with check constaints

### ISSUE THREAD

**Issue by yhilmare** [oceanbase/odc#195]
### ODC version

4.2.0

### OB version

not related

### What happened?

create a table as follow:
```SQL
CREATE TABLE "SHILIN"."A11" (
  "qq" NUMBER(*,0),
  "AA" NUMBER(*,0),
  "ww" VARCHAR2(120),
  CONSTRAINT "T" CHECK (("AA" >= 0)) ENABLE
)
```

attempt to mock data on it, and you will get a error:
```shell
2023-03-01 11:05:11 WARN c.o.o.s.f.t.MockDataRuntimeFlowableTask - Mock data task failed, taskId=16062925
2023-03-01 11:05:11 WARN c.o.o.s.f.t.MockDataRuntimeFlowableTask - Mock data task failed, taskId=16062925
com.oceanbase.tools.datamocker.model.exception.MockerException: Check constraint is not support yet, ("AA" >= 0)
 	at com.oceanbase.tools.datamocker.core.task.AbstractMockerFactory.create(AbstractMockerFactory.java:130) ~[ob-mocker-0.1.3-SNAPSHOT.jar!/:?]
 	at com.oceanbase.odc.service.flow.task.MockDataRuntimeFlowableTask.start(MockDataRuntimeFlowableTask.java:88) [classes!/:?]
 	at com.oceanbase.odc.service.flow.task.MockDataRuntimeFlowableTask.start(MockDataRuntimeFlowableTask.java:36) [classes!/:?]
```

### What did you expect to happen?

mock data succeed.

### How can we reproduce it (as minimally and precisely as possible)?

follow 'What happened'

**Comment by yhilmare** [comment]
the table with check constraint is not supported yet which is expected~
