### ISSUE TITLE
[Bug]: The creation of cycle execution and the specified task duration archiving task failed, npe

### ISSUE THREAD

**Issue by Huangxiao-mas** [oceanbase/odc#2484]
### ODC version

ODC430

### OB version

Oceanbase430

### What happened?

The creation of cycle execution and the specified task duration archiving task failed, npe
```
 1 2024-05-23 16:51:05 [INFO] begin to init datasource OBMYSQL: null
2 2024-05-23 16:51:05 [INFO] No Sys tenant user or init sys datasource failed.
3 2024-05-23 16:51:05 [INFO] set sleep time = 50
4 2024-05-23 16:51:05 [INFO] begin to init datasource OBMYSQL: null
5 2024-05-23 16:51:05 [INFO] No Sys tenant user or init sys datasource failed.
6 2024-05-23 16:51:05 [INFO] set sleep time = 50
7 2024-05-23 16:51:05 [INFO] set primary table meta use source table meta
8 2024-05-23 16:51:05 [WARN] Create job meta failed,error=
9 java.lang.NullPointerException: null
10 	at com.oceanbase.tools.migrator.core.JobMetaFactory.create(JobMetaFactory.java:71) [data-lifecycle-manager-1.1.2.jar!/:?]
11 	at com.oceanbase.tools.migrator.core.JobFactory.createJob(JobFactory.java:38) [data-lifecycle-manager-1.1.2.jar!/:?]
12 	at com.oceanbase.odc.service.dlm.DLMJobFactory.createJob(DLMJobFactory.java:82) [odc-service-4.3.0-20240522.jar!/:?]
13 	at com.oceanbase.odc.service.schedule.job.AbstractDlmJob.executeTask(AbstractDlmJob.java:129) [odc-service-4.3.0-20240522.jar!/:?]
14 	at com.oceanbase.odc.service.schedule.job.DataArchiveJob.executeJob(DataArchiveJob.java:55) [odc-service-4.3.0-20240522.jar!/:?]
15 	at com.oceanbase.odc.service.schedule.job.AbstractDlmJob.execute(AbstractDlmJob.java:259) [odc-service-4.3.0-20240522.jar!/:?]
16 	at com.oceanbase.odc.service.quartz.executor.AbstractQuartzJob.run(AbstractQuartzJob.java:67) [odc-service-4.3.0-20240522.jar!/:?]
17 	at com.oceanbase.odc.service.quartz.executor.QuartzJob.run(QuartzJob.java:33) [odc-service-4.3.0-20240522.jar!/:?]
18 	at com.oceanbase.odc.service.quartz.executor.AbstractQuartzJob.execute(AbstractQuartzJob.java:54) [odc-service-4.3.0-20240522.jar!/:?]
19 	at org.quartz.core.JobRunShell.run(JobRunShell.java:202) [quartz-2.3.2.jar!/:?]
20 	at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573) [quartz-2.3.2.jar!/:?]
21 2024-05-23 16:51:05 [WARN] Create job failed
22 java.lang.NullPointerException: null
23 	at com.oceanbase.tools.migrator.core.JobMetaFactory.create(JobMetaFactory.java:71) ~[data-lifecycle-manager-1.1.2.jar!/:?]
24 	at com.oceanbase.tools.migrator.core.JobFactory.createJob(JobFactory.java:38) [data-lifecycle-manager-1.1.2.jar!/:?]
25 	at com.oceanbase.odc.service.dlm.DLMJobFactory.createJob(DLMJobFactory.java:82) [odc-service-4.3.0-20240522.jar!/:?]
26 	at com.oceanbase.odc.service.schedule.job.AbstractDlmJob.executeTask(AbstractDlmJob.java:129) [odc-service-4.3.0-20240522.jar!/:?]
27 	at com.oceanbase.odc.service.schedule.job.DataArchiveJob.executeJob(DataArchiveJob.java:55) [odc-service-4.3.0-20240522.jar!/:?]
28 	at com.oceanbase.odc.service.schedule.job.AbstractDlmJob.execute(AbstractDlmJob.java:259) [odc-service-4.3.0-20240522.jar!/:?]
29 	at com.oceanbase.odc.service.quartz.executor.AbstractQuartzJob.run(AbstractQuartzJob.java:67) [odc-service-4.3.0-20240522.jar!/:?]
30 	at com.oceanbase.odc.service.quartz.executor.QuartzJob.run(QuartzJob.java:33) [odc-service-4.3.0-20240522.jar!/:?]
31 	at com.oceanbase.odc.service.quartz.executor.AbstractQuartzJob.execute(AbstractQuartzJob.java:54) [odc-service-4.3.0-20240522.jar!/:?]
32 	at org.quartz.core.JobRunShell.run(JobRunShell.java:202) [quartz-2.3.2.jar!/:?]
33 	at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573) [quartz-2.3.2.jar!/:?]
34 2024-05-23 16:51:11 [INFO] begin to init datasource OBMYSQL: null
35 2024-05-23 16:51:11 [INFO] No Sys tenant user or init sys datasource failed.
36 2024-05-23 16:51:11 [INFO] set sleep time = 50
37 2024-05-23 16:51:11 [INFO] begin to init datasource OBMYSQL: null
38 2024-05-23 16:51:11 [INFO] No Sys tenant user or init sys datasource failed.
39 2024-05-23 16:51:11 [INFO] set sleep time = 50
40 2024-05-23 16:51:11 [INFO] set primary table meta use source table meta
41 2024-05-23 16:51:11 [WARN] Create job meta failed,error=
42 java.lang.NullPointerException: null
43 	at com.oceanbase.tools.migrator.core.JobMetaFactory.create(JobMetaFactory.java:71) [data-lifecycle-manager-1.1.2.jar!/:?]
44 	at com.oceanbase.tools.migrator.core.JobFactory.createJob(JobFactory.java:38) [data-lifecycle-manager-1.1.2.jar!/:?]
45 	at com.oceanbase.odc.service.dlm.DLMJobFactory.createJob(DLMJobFactory.java:82) [odc-service-4.3.0-20240522.jar!/:?]
46 	at com.oceanbase.odc.service.schedule.job.AbstractDlmJob.executeTask(AbstractDlmJob.java:129) [odc-service-4.3.0-20240522.jar!/:?]
47 	at com.oceanbase.odc.service.schedule.job.DataArchiveJob.executeJob(DataArchiveJob.java:55) [odc-service-4.3.0-20240522.jar!/:?]
48 	at com.oceanbase.odc.service.schedule.job.AbstractDlmJob.execute(AbstractDlmJob.java:259) [odc-service-4.3.0-20240522.jar!/:?]
49 	at com.oceanbase.odc.service.quartz.executor.AbstractQuartzJob.run(AbstractQuartzJob.java:67) [odc-service-4.3.0-20240522.jar!/:?]
50 	at com.oceanbase.odc.service.quartz.executor.QuartzJob.run(QuartzJob.java:33) [odc-service-4.3.0-20240522.jar!/:?]
51 	at com.oceanbase.odc.service.quartz.executor.AbstractQuartzJob.execute(AbstractQuartzJob.java:54) [odc-service-4.3.0-20240522.jar!/:?]
52 	at org.quartz.core.JobRunShell.run(JobRunShell.java:202) [quartz-2.3.2.jar!/:?]
53 	at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573) [quartz-2.3.2.jar!/:?]
54 2024-05-23 16:51:11 [WARN] Create job failed
55 java.lang.NullPointerException: null
56 	at com.oceanbase.tools.migrator.core.JobMetaFactory.create(JobMetaFactory.java:71) ~[data-lifecycle-manager-1.1.2.jar!/:?]
57 	at com.oceanbase.tools.migrator.core.JobFactory.createJob(JobFactory.java:38) [data-lifecycle-manager-1.1.2.jar!/:?]
58 	at com.oceanbase.odc.service.dlm.DLMJobFactory.createJob(DLMJobFactory.java:82) [odc-service-4.3.0-20240522.jar!/:?]
59 	at com.oceanbase.odc.service.schedule.job.AbstractDlmJob.executeTask(AbstractDlmJob.java:129) [odc-service-4.3.0-20240522.jar!/:?]
60 	at com.oceanbase.odc.service.schedule.job.DataArchiveJob.executeJob(DataArchiveJob.java:55) [odc-service-4.3.0-20240522.jar!/:?]
61 	at com.oceanbase.odc.service.schedule.job.AbstractDlmJob.execute(AbstractDlmJob.java:259) [odc-service-4.3.0-20240522.jar!/:?]
62 	at com.oceanbase.odc.service.quartz.executor.AbstractQuartzJob.run(AbstractQuartzJob.java:67) [odc-service-4.3.0-20240522.jar!/:?]
63 	at com.oceanbase.odc.service.quartz.executor.QuartzJob.run(QuartzJob.java:33) [odc-service-4.3.0-20240522.jar!/:?]
64 	at com.oceanbase.odc.service.quartz.executor.AbstractQuartzJob.execute(AbstractQuartzJob.java:54) [odc-service-4.3.0-20240522.jar!/:?]
65 	at org.quartz.core.JobRunShell.run(JobRunShell.java:202) [quartz-2.3.2.jar!/:?]
66 	at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573) [quartz-2.3.2.jar!/:?]
67 

```

### What did you expect to happen?

.

### How can we reproduce it (as minimally and precisely as possible)?

```
taskId 39
chat privately
```

**Comment by Huangxiao-mas** [comment]
test pass
