### ISSUE TITLE
[Bug]: ODC inaccessible, only recovered after reboot

### ISSUE THREAD

**Issue by smallsheeeep** [oceanbase/odc#260]
### ODC version

3.3.4

### OB version

Not yet provide

### What happened?

ODC inaccessible, only recovered after reboot

### What did you expect to happen?

<null>

### How can we reproduce it (as minimally and precisely as possible)?

Error message:
```shell
[2023-09-07 14:05:05.055][http-nio-8989-exec-57][50683bcf72e84369,,1U1PGAJTH4RTYJG9DWSTVE][WARN][com.oceanbase.odc.web.controller.RestExceptionHandler][314]: Unhandled checked exception:
org.springframework.orm.jpa.JpaSystemException: Unable to commit against JDBC Connection; nested exception is org.hibernate.TransactionException: Unable to commit against JDBC Connection
        at org.springframework.orm.jpa.vendor.HibernateJpaDialect.convertHibernateAccessException(HibernateJpaDialect.java:353) ~[spring-orm-5.2.12.RELEASE.jar!/:5.2.12.RELEASE]
        at org.springframework.orm.jpa.vendor.HibernateJpaDialect.translateExceptionIfPossible(HibernateJpaDialect.java:255) ~[spring-orm-5.2.12.RELEASE.jar!/:5.2.12.RELEASE]
        at org.springframework.orm.jpa.JpaTransactionManager.doCommit(JpaTransactionManager.java:538) ~[spring-orm-5.2.12.RELEASE.jar!/:5.2.12.RELEASE]
        at org.springframework.transaction.support.AbstractPlatformTransactionManager.processCommit(AbstractPlatformTransactionManager.java:743) ~[spring-tx-5.2.21.RELEASE.jar!/:5.2.21.RELEASE]
        at org.springframework.transaction.support.AbstractPlatformTransactionManager.commit(AbstractPlatformTransactionManager.java:711) ~[spring-tx-5.2.21.RELEASE.jar!/:5.2.21.RELEASE]
        at org.springframework.transaction.interceptor.TransactionAspectSupport.commitTransactionAfterReturning(TransactionAspectSupport.java:633) ~[spring-tx-5.2.21.RELEASE.jar!/:5.2.21.RELEASE]
        at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:386) ~[spring-tx-5.2.21.RELEASE.jar!/:5.2.21.RELEASE]
        at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:118) ~[spring-tx-5.2.21.RELEASE.jar!/:5.2.21.RELEASE]
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) ~[spring-aop-5.2.12.RELEASE.jar!/:5.2.12.RELEASE]
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:749) ~[spring-aop-5.2.12.RELEASE.jar!/:5.2.12.RELEASE]
        at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:691) ~[spring-aop-5.2.12.RELEASE.jar!/:5.2.12.RELEASE]
        at com.oceanbase.odc.service.connection.ConnectionService$$EnhancerBySpringCGLIB$$5328b190.create(<generated>) ~[classes!/:?]
        at com.oceanbase.odc.web.controller.ConnectConnectionController.createConnection(ConnectConnectionController.java:132) ~[classes!/:?]
        at com.oceanbase.odc.web.controller.ConnectConnectionController$$FastClassBySpringCGLIB$$9cd29d18.invoke(<generated>) ~[classes!/:?]
Caused by: java.sql.SQLException: Transaction is timeout
        at com.oceanbase.jdbc.internal.protocol.AbstractQueryProtocol.readErrorPacket(AbstractQueryProtocol.java:1973) ~[oceanbase-client-2.2.6.jar!/:?]
        at com.oceanbase.jdbc.internal.protocol.AbstractQueryProtocol.readPacket(AbstractQueryProtocol.java:1838) ~[oceanbase-client-2.2.6.jar!/:?]
        at com.oceanbase.jdbc.internal.protocol.AbstractQueryProtocol.getResult(AbstractQueryProtocol.java:1728) ~[oceanbase-client-2.2.6.jar!/:?]
        at com.oceanbase.jdbc.internal.protocol.AbstractQueryProtocol.executeQuery(AbstractQueryProtocol.java:300) ~[oceanbase-client-2.2.6.jar!/:?]
        at com.oceanbase.jdbc.OceanBaseStatement.executeInternal(OceanBaseStatement.java:371) ~[oceanbase-client-2.2.6.jar!/:?]
        at com.oceanbase.jdbc.OceanBaseStatement.execute(OceanBaseStatement.java:515) ~[oceanbase-client-2.2.6.jar!/:?]
        at com.oceanbase.jdbc.OceanBaseConnection.commit(OceanBaseConnection.java:876) ~[oceanbase-client-2.2.6.jar!/:?]
        at com.alibaba.druid.pool.DruidPooledConnection.commit(DruidPooledConnection.java:755) ~[druid-1.1.23.jar!/:1.1.23]
        at org.hibernate.resource.jdbc.internal.AbstractLogicalConnectionImplementor.commit(AbstractLogicalConnectionImplementor.java:86) ~[hibernate-core-5.4.27.Final.jar!/:5.4.27.Final]
        at org.hibernate.resource.transaction.backend.jdbc.internal.JdbcResourceLocalTransactionCoordinatorImpl$TransactionDriverControlImpl.commit(JdbcResourceLocalTransactionCoordinatorImpl.java:282) ~[hibernate-core-5.4.27.Final.jar!/:5.4.27.Final]
        at org.hibernate.engine.transaction.internal.TransactionImpl.commit(TransactionImpl.java:101) ~[hibernate-core-5.4.27.Final.jar!/:5.4.27.Final]
        at org.springframework.orm.jpa.JpaTransactionManager.doCommit(JpaTransactionManager.java:534) ~[spring-orm-5.2.12.RELEASE.jar!/:5.2.12.RELEASE]
        ... 127 more


[2023-09-07 14:05:05.056][http-nio-8989-exec-108][41632a24d62b4bcb,,LBRP5XGTTQECIO37UYEWL][WARN][com.oceanbase.odc.web.controller.RestExceptionHandler][314]: Unhandled checked exception:
org.springframework.jdbc.CannotGetJdbcConnectionException: Failed to obtain JDBC Connection; nested exception is com.alibaba.druid.pool.GetConnectionTimeoutException: wait millis 25846, active 2, maxActive 5, creating 1, createElapseMillis 35689
        at org.springframework.jdbc.datasource.DataSourceUtils.getConnection(DataSourceUtils.java:82) ~[spring-jdbc-5.2.21.RELEASE.jar!/:5.2.21.RELEASE]
        at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:371) ~[spring-jdbc-5.2.21.RELEASE.jar!/:5.2.21.RELEASE]
        at org.springframework.jdbc.core.JdbcTemplate.query(JdbcTemplate.java:452) ~[spring-jdbc-5.2.21.RELEASE.jar!/:5.2.21.RELEASE]
        at org.springframework.jdbc.core.JdbcTemplate.query(JdbcTemplate.java:462) ~[spring-jdbc-5.2.21.RELEASE.jar!/:5.2.21.RELEASE]
        at com.alipay.odc.odcsdk.connect.core.GeneralSyncJdbcExecutor.query(GeneralSyncJdbcExecutor.java:80) ~[ob-odc-sdk-3.3.4-20220830.jar!/:?]
        at com.alipay.odc.odcsdk.accessor.oracle.OracleSchemaAccessor.listAllUserViews(OracleSchemaAccessor.java:87) ~[ob-odc-sdk-3.3.4-20220830.jar!/:?]
        at com.oceanbase.odc.service.db.identity.DBIdentitiesService.listViews(DBIdentitiesService.java:44) ~[classes!/:?]
        at com.oceanbase.odc.service.db.identity.DBIdentitiesService.list(DBIdentitiesService.java:30) ~[classes!/:?]
        at com.oceanbase.odc.web.controller.DBMetadataController.listIdentities(DBMetadataController.java:29) ~[classes!/:?]
Caused by: com.alibaba.druid.pool.GetConnectionTimeoutException: wait millis 25846, active 2, maxActive 5, creating 1, createElapseMillis 35689
        at com.alibaba.druid.pool.DruidDataSource.getConnectionInternal(DruidDataSource.java:1734) ~[druid-1.1.23.jar!/:1.1.23]
        at com.alibaba.druid.pool.DruidDataSource.getConnectionDirect(DruidDataSource.java:1404) ~[druid-1.1.23.jar!/:1.1.23]
        at com.alibaba.druid.pool.DruidDataSource.getConnection(DruidDataSource.java:1384) ~[druid-1.1.23.jar!/:1.1.23]
        at com.alibaba.druid.pool.DruidDataSource.getConnection(DruidDataSource.java:1374) ~[druid-1.1.23.jar!/:1.1.23]
        at com.alibaba.druid.pool.DruidDataSource.getConnection(DruidDataSource.java:98) ~[druid-1.1.23.jar!/:1.1.23]
        at com.alipay.odc.odcsdk.connect.datasource.ProxyDataSource.getConnection(ProxyDataSource.java:53) ~[ob-odc-sdk-3.3.4-20220830.jar!/:?]
        at org.springframework.jdbc.datasource.DataSourceUtils.fetchConnection(DataSourceUtils.java:158) ~[spring-jdbc-5.2.21.RELEASE.jar!/:5.2.21.RELEASE]
        at org.springframework.jdbc.datasource.DataSourceUtils.doGetConnection(DataSourceUtils.java:116) ~[spring-jdbc-5.2.21.RELEASE.jar!/:5.2.21.RELEASE]
        at org.springframework.jdbc.datasource.DataSourceUtils.getConnection(DataSourceUtils.java:79) ~[spring-jdbc-5.2.21.RELEASE.jar!/:5.2.21.RELEASE]
        ... 125 more

[2023-09-07 13:41:00.646][flowable-reset-expired-jobs][,,][ERROR][org.flowable.common.engine.impl.interceptor.CommandContext][115]: Error while closing command context
java.lang.NullPointerException: null
        at org.flowable.engine.impl.util.CountingEntityUtil.isExecutionRelatedEntityCountEnabled(CountingEntityUtil.java:81) ~[flowable-engine-6.3.1.jar!/:6.3.1]
        at org.flowable.engine.impl.cfg.DefaultInternalJobManager.handleJobDelete(DefaultInternalJobManager.java:121) ~[flowable-engine-6.3.1.jar!/:6.3.1]
        at org.flowable.job.service.impl.persistence.entity.JobEntityManagerImpl.delete(JobEntityManagerImpl.java:93) ~[flowable-job-service-6.3.1.jar!/:6.3.1]
        at org.flowable.job.service.impl.persistence.entity.JobEntityManagerImpl.delete(JobEntityManagerImpl.java:32) ~[flowable-job-service-6.3.1.jar!/:6.3.1]
        at org.flowable.job.service.impl.persistence.entity.AbstractEntityManager.delete(AbstractEntityManager.java:88) ~[flowable-job-service-6.3.1.jar!/:6.3.1]
        at org.flowable.job.service.impl.persistence.entity.JobEntityManagerImpl.delete(JobEntityManagerImpl.java:79) ~[flowable-job-service-6.3.1.jar!/:6.3.1]
        at org.flowable.job.service.impl.persistence.entity.JobEntityManagerImpl.delete(JobEntityManagerImpl.java:32) ~[flowable-job-service-6.3.1.jar!/:6.3.1]
        at org.flowable.job.service.impl.persistence.entity.AbstractEntityManager.delete(AbstractEntityManager.java:83) ~[flowable-job-service-6.3.1.jar!/:6.3.1]
        at org.flowable.job.service.impl.asyncexecutor.DefaultJobManager.unacquire(DefaultJobManager.java:267) ~[flowable-job-service-6.3.1.jar!/:6.3.1]
        at org.flowable.job.service.impl.asyncexecutor.ResetExpiredJobsCmd.execute(ResetExpiredJobsCmd.java:41) ~[flowable-job-service-6.3.1.jar!/:6.3.1]
        at org.flowable.job.service.impl.asyncexecutor.ResetExpiredJobsCmd.execute(ResetExpiredJobsCmd.java:27) ~[flowable-job-service-6.3.1.jar!/:6.3.1]
        at org.flowable.engine.impl.interceptor.CommandInvoker$1.run(CommandInvoker.java:51) ~[flowable-engine-6.3.1.jar!/:6.3.1]
        at org.flowable.engine.impl.interceptor.CommandInvoker.executeOperation(CommandInvoker.java:93) ~[flowable-engine-6.3.1.jar!/:6.3.1]
        at org.flowable.engine.impl.interceptor.CommandInvoker.executeOperations(CommandInvoker.java:72) ~[flowable-engine-6.3.1.jar!/:6.3.1]
        at org.flowable.engine.impl.interceptor.CommandInvoker.execute(CommandInvoker.java:56) ~[flowable-engine-6.3.1.jar!/:6.3.1]
        at org.flowable.engine.impl.interceptor.BpmnOverrideContextInterceptor.execute(BpmnOverrideContextInterceptor.java:25) ~[flowable-engine-6.3.1.jar!/:6.3.1]
        at org.flowable.common.engine.impl.interceptor.TransactionContextInterceptor.execute(TransactionContextInterceptor.java:53) ~[flowable-engine-common-6.3.1.jar!/:6.3.1]
        at org.flowable.common.engine.impl.interceptor.CommandContextInterceptor.execute(CommandContextInterceptor.java:71) [flowable-engine-common-6.3.1.jar!/:6.3.1]
        at org.flowable.common.engine.impl.interceptor.LogInterceptor.execute(LogInterceptor.java:30) [flowable-engine-common-6.3.1.jar!/:6.3.1]
        at org.flowable.common.engine.impl.cfg.CommandExecutorImpl.execute(CommandExecutorImpl.java:56) [flowable-engine-common-6.3.1.jar!/:6.3.1]
        at org.flowable.common.engine.impl.cfg.CommandExecutorImpl.execute(CommandExecutorImpl.java:51) [flowable-engine-common-6.3.1.jar!/:6.3.1]
        at org.flowable.job.service.impl.asyncexecutor.ResetExpiredJobsRunnable.run(ResetExpiredJobsRunnable.java:72) [flowable-job-service-6.3.1.jar!/:6.3.1]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_312]


[2023-09-07 14:06:09.047][scheduling-1][,,][ERROR][org.springframework.scheduling.support.TaskUtils$LoggingErrorHandler][95]: Unexpected error occurred in scheduled task
java.lang.IllegalStateException: Duplicate key ServiceTaskInstanceEntity(id=124001765, organizationId=1, targetTaskId=124001758, strategy=AUTO, taskType=ASYNC, waitExecExpireIntervalSeconds=-1, status=CREATED, startEndpoint=false, endEndpoint=false, flowInstanceId=124001758, createTime=2023-09-06 16:53:48.0, updateTime=2023-09-06 16:53:48.0)
        at java.util.stream.Collectors.lambda$throwingMerger$0(Collectors.java:133) ~[?:1.8.0_312]
        at java.util.HashMap.merge(HashMap.java:1255) ~[?:1.8.0_312]
        at java.util.stream.Collectors.lambda$toMap$58(Collectors.java:1320) ~[?:1.8.0_312]
        at java.util.stream.ReduceOps$3ReducingSink.accept(ReduceOps.java:169) ~[?:1.8.0_312]
        at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1384) ~[?:1.8.0_312]
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482) ~[?:1.8.0_312]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472) ~[?:1.8.0_312]
        at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708) ~[?:1.8.0_312]
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:1.8.0_312]
        at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:566) ~[?:1.8.0_312]
        at com.oceanbase.odc.integration.chinamobile.InterceptFlowAdaptor$TaskFlowContexts.fetchTaskInstance(InterceptFlowAdaptor.java:163) ~[classes!/:?]
        at com.oceanbase.odc.integration.chinamobile.InterceptFlowAdaptor$TaskFlowContexts.init(InterceptFlowAdaptor.java:120) ~[classes!/:?]
        at com.oceanbase.odc.integration.chinamobile.InterceptFlowAdaptor.handleTaskForConfirmingFlow(InterceptFlowAdaptor.java:86) ~[classes!/:?]
        at com.oceanbase.odc.integration.chinamobile.InterceptSchedules.handleConfirmFlow(InterceptSchedules.java:14) ~[classes!/:?]
        at sun.reflect.GeneratedMethodAccessor300.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_312]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_312]
        at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:84) ~[spring-context-5.2.21.RELEASE.jar!/:5.2.21.RELEASE]
        at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) [spring-context-5.2.21.RELEASE.jar!/:5.2.21.RELEASE]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_312]
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) [?:1.8.0_312]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_312]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [?:1.8.0_312]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_312]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_312]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_312]
```

**Comment by yhilmare** [comment]
It is caused by an operation transaction timeout of creating a connection. At this time, the connection pool of odc tries to create a new connection to the metadata database, but the server does not respond and triggers a timeout. You can check to see if your metadata size is small, or if the load is too heavy at that moment, this should not be a bug of odc
